{% set name = "python-novaclient" %}
{% set version = "18.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ead3db2a3dd43a89bb5a56f62f87362a76e7ef9c01938699ff6c1a060f0e9eab

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - nova = novaclient.shell:main

requirements:
  host:
    - pbr
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - pbr
    - keystoneauth1 >=3.5.0
    - iso8601 >=0.1.11
    - oslo.i18n >=3.15.3
    - oslo.serialization >2.19.1
    - oslo.utils >=3.33.0
    - prettytable >=0.7.2
    - python >={{ python_min }}
    - stevedore >=2.0.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - novaclient

about:
  home: https://docs.openstack.org/python-novaclient/latest
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Client library for OpenStack Compute API
  doc_url: https://docs.openstack.org/python-novaclient/latest
  dev_url: https://opendev.org/openstack/python-novaclient

extra:
  recipe-maintainers:
    - tschoonj
